name: 'Self-hosted GH CLI'
description: 'Download, cache and install the GitHub CLI to the workspace'
author: 'alexnorell'
inputs:
  cli-release:
    description: 'Version of the GitHub-CLI that should be installed'
    required: false
    default: 'latest'
  arch:
    description: 'Architecture to download and install'
    required: false
    default: 'amd64'
  platform:
    description: 'Platform to download and install'
    required: false
    default: 'linux'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'arrow-down'
  color: 'purple'
