name: Test Action
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test-default:
    name: Test Action Defaults (Linux)
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install GH CLI
        uses: alexnorell/install-gh-cli-action@main
      - name: git describe
        id: ghd
        uses: proudust/gh-describe@v1
  test-latest:
    name: Test Action Latest (Linux)
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install GH CLI
        uses: alexnorell/install-gh-cli-action@main
        with:
          cli-release: latest
      - name: git describe
        id: ghd
        uses: proudust/gh-describe@v1
  test-specific:
    name: Test Action Specific Version (Linux)
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install GH CLI
        uses: alexnorell/install-gh-cli-action@main
        with:
          cli-release: v2.36.0
      - name: git describe
        id: ghd
        uses: proudust/gh-describe@v1
